### PR TITLE
Implements working getMaps function in handlers.js

### PR DESCRIPTION
**Pull request by wesleysmyth**
Hey guys - I've got a working getMaps function going on in handlers.js.  Only thing is I'll need to refactor the final return statement for the wholeMap to not use a setTimeout.  It's working for now, but for larger data pulls this will need to change.  I'm going to look into changing this, but feel free to check it out and help as well.

### CODE REVIEW

**Comment by Radiobeat33** [comment]
Nice work man, Henry and I are gonna get a bulk of the front end up and running tomorrow. Thanks for the update!

**Comment by wesleysmyth** [comment]
Hey guys, just realized I accidentally closed this myself in waffle.io.  Please check it out and feel free to merge if all looks good.

**Comment by nlokare** [comment]
I am having some major issues merge Wes' pull request. @wesleysmyth would you be able to merge your own. I've reviewed and it looks great, but I am having some major issues here.

**Comment by wesleysmyth** [comment]
Hey guys, I'm going to close this request and try creating a new one...

**Pull request closed without merging**
